=== lounisakkache/XML/bibliographie.dtd
<!ELEMENT bibliographie (titre,article*,livre*)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT article (titre,auteurs,uri)>
<!ATTLIST article type CDATA #REQUIRED>
<!ELEMENT auteurs (nom+,editeur?)>
<!ELEMENT nom ( #PCDATA)>
<!ELEMENT editeur ( #PCDATA)>
<!ELEMENT uri ( #PCDATA)>
<!ELEMENT livre (titre,auteurs)>
<!ATTLIST livre xml:lang CDATA  #REQUIRED>

=== lounisakkache/XML/bibliographie.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE bibliographie SYSTEM "bibliographie.dtd">
<bibliographie>
    <titre>Calcul Quantique</titre>

    <article type="non publiÃ©">
        <titre>Quantum Proofs for Classical Theorem</titre>
        <auteurs>
            <nom>Drucker</nom>
            <nom>de Wolf</nom>
        </auteurs>
        <uri>arxiv:quant-ph/0910.3376v1</uri>
    </article>
    <livre xml:lang = "en">
        <titre>Quantum Computation and Quantum Information</titre>
        <auteurs>
                <nom>Nielsen</nom>
                <nom>Chuang</nom>
                <editeur>Cambridge U. Press</editeur>
        </auteurs>
    </livre>
    </bibliographie>
